CC = gcc

CFLAGS=-g

proj6: proj6.o frac_heap.o 
	gcc $^ -o $@

test1.out: test1.o frac_heap.o
	gcc $^ -o $@

test2.out: test2.o frac_heap.o
	gcc $^ -o $@

test3.out: test3.o frac_heap.o
	gcc $^ -o $@

test4.out: test4.o frac_heap.o
	gcc $^ -o $@

test5.out: test5.o frac_heap.o
	gcc $^ -o $@

test6.out: test6.o frac_heap.o
	gcc $^ -o $@

clean:
	rm -f *.o *.out *.lst *~
